HealthCare/Controllers/DoctorAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using HealthCare.Models;
using HealthCare.Context;

namespace HealthCare.Controllers
{
    public class DoctorAdminController : Controller
    {
        private HealthContext db = new HealthContext();
        PrivacyController privacy=new PrivacyController();
        public static string EncodePassword(string password)
        {
            Byte[] originalBytes;
            Byte[] encodedBytes;
            MD5 a;
            a = new MD5CryptoServiceProvider();
            originalBytes = ASCIIEncoding.Default.GetBytes(password);
            encodedBytes = a.ComputeHash(originalBytes);
            return BitConverter.ToString(encodedBytes);
        }

        // GET: /DoctorAdmin/
        public ActionResult Index()
        {

            List<Doctor> doctors = db.Doctors.ToList();
            foreach (Doctor doc in doctors)
            {
                
                doc.Name = privacy.Decrypt(doc.Name);
                doc.Degree = privacy.Decrypt(doc.Degree);
                doc.Email = privacy.Decrypt(doc.Email);
            }
            return View(doctors);
        }

        // GET: /DoctorAdmin/Details/5
       

        // GET: /DoctorAdmin/Create
        public ActionResult Create()
        {
            ViewBag.Specialist = db.Specialist.ToList();
            return View();
        }

        // POST: /DoctorAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image,Degree,Fees,Schedule,CategoryId,Email,Password")] Doctor doctor, HttpPostedFileBase Image, int categoryId)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        doctor.Image = "picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                doctor.CategoryId = categoryId;
                doctor.Name = privacy.Encrypt(doctor.Name);
                doctor.Email = privacy.Encrypt(doctor.Email);
                doctor.Degree = privacy.Encrypt(doctor.Degree);
                doctor.Schedule = doctor.Schedule;
                doctor.Password = EncodePassword(doctor.Password);
                db.Doctors.Add(doctor);
                db.SaveChanges();
            }

            return RedirectToAction("Create", new { message = "Doctor Successfully Appointed" });
        }

        // GET: /DoctorAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.DoctorCategory = db.Specialist.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            doctor.Name = privacy.Decrypt(doctor.Name);
            doctor.Email = privacy.Decrypt(doctor.Email);
            doctor.Degree = privacy.Decrypt(doctor.Degree);
            return View(doctor);
        }

        // POST: /DoctorAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image,Degree,Fees,Schedule,CategoryId,Email,Password")] Doctor doctor, HttpPostedFileBase Image, int categoryId, string pastImage)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {

                    try
                    {
                        string fileName = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(Image.FileName);
                        string uploadUrl = Server.MapPath("~/picture");
                        Image.SaveAs(Path.Combine(uploadUrl, fileName));
                        doctor.Image = "picture/" + fileName;
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                {
                    doctor.Image = pastImage;
                }
                doctor.CategoryId = categoryId;
                doctor.Name = privacy.Encrypt(doctor.Name);
                doctor.Email = privacy.Encrypt(doctor.Email);
                doctor.Degree = privacy.Encrypt(doctor.Degree);
                doctor.Schedule = doctor.Schedule;
                doctor.Password = EncodePassword(doctor.Password);
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: /DoctorAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            doctor.Name = privacy.Decrypt(doctor.Name);
            doctor.Degree = privacy.Decrypt(doctor.Degree);
            doctor.Email = privacy.Decrypt(doctor.Email);
            return View(doctor);
        }

        // POST: /DoctorAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthCare/Controllers/ReceptionistAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using HealthCare.Models;
using HealthCare.Context;

namespace HealthCare.Controllers
{
    public class ReceptionistAdminController : Controller
    {
        private HealthContext db = new HealthContext();
        PrivacyController privacy=new PrivacyController();
        public static string EncodePassword(string password)
        {
            Byte[] originalBytes;
            Byte[] encodedBytes;
            MD5 a;
            a = new MD5CryptoServiceProvider();
            originalBytes = ASCIIEncoding.Default.GetBytes(password);
            encodedBytes = a.ComputeHash(originalBytes);
            return BitConverter.ToString(encodedBytes);
        }
        // GET: /ReceptionistAdmin/
        public ActionResult Index()
        {
            List<Receptionist> receptionists = db.Receptionist.ToList();
            foreach (Receptionist rep in receptionists)
            {

                rep.Name = privacy.Decrypt(rep.Name);
                rep.Address = privacy.Decrypt(rep.Address);
                rep.PhoneNo = privacy.Decrypt(rep.PhoneNo);
                rep.Email = privacy.Decrypt(rep.Email);
            }
            return View(receptionists);
        }

        // GET: /ReceptionistAdmin/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Receptionist receptionist = db.Receptionist.Find(id);
        //    if (receptionist == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(receptionist);
        //}

        // GET: /ReceptionistAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ReceptionistAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,PhoneNo,Address,Email,Password")] Receptionist receptionist)
        {
            receptionist.Email = privacy.Encrypt(receptionist.Email);
            var e = db.Doctors.Where(c => c.Email == receptionist.Email).ToList().Count;
            if (e == 0)
            {
                if (ModelState.IsValid)
                {
                    receptionist.Name = privacy.Encrypt(receptionist.Name);
                    receptionist.Address = privacy.Encrypt(receptionist.Address);
                    receptionist.PhoneNo = privacy.Encrypt(receptionist.PhoneNo);
                    receptionist.Password = EncodePassword(receptionist.Password);
                    db.Receptionist.Add(receptionist);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.Message = "Insert Values Successfully";
            }

            else
            {
                ViewBag.Message = "Email Already exists";
            }
            return View(receptionist);
        }

        // GET: /ReceptionistAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receptionist receptionist = db.Receptionist.Find(id);
            if (receptionist == null)
            {
                return HttpNotFound();
            }
            receptionist.Name = privacy.Decrypt(receptionist.Name);
            receptionist.Address = privacy.Decrypt(receptionist.Address);
            receptionist.Email = privacy.Decrypt(receptionist.Email);
            receptionist.PhoneNo = privacy.Decrypt(receptionist.PhoneNo);
            return View(receptionist);
        }

        // POST: /ReceptionistAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,PhoneNo,Address,Email,Password")] Receptionist receptionist)
        {
            if (ModelState.IsValid)
            {
                receptionist.Name = privacy.Encrypt(receptionist.Name);
                receptionist.Email = privacy.Encrypt(receptionist.Email);
                receptionist.Password = EncodePassword(receptionist.Password);
                receptionist.Address = privacy.Encrypt(receptionist.Address);
                receptionist.PhoneNo = privacy.Encrypt(receptionist.PhoneNo);
                db.Entry(receptionist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Message = "Update Values Successfully";
            return View(receptionist);
        }

        // GET: /ReceptionistAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receptionist receptionist = db.Receptionist.Find(id);
            if (receptionist == null)
            {
                return HttpNotFound();
            }
            receptionist.Name = privacy.Decrypt(receptionist.Name);
            receptionist.Address = privacy.Decrypt(receptionist.Address);
            receptionist.Email = privacy.Decrypt(receptionist.Email);
            receptionist.PhoneNo = privacy.Decrypt(receptionist.PhoneNo);
            return View(receptionist);
        }

        // POST: /ReceptionistAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Receptionist receptionist = db.Receptionist.Find(id);
            db.Receptionist.Remove(receptionist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthCare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title HealthCare</title>
    <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet" />

    <style>
        @@media (max-width: 576px) {
            .gone {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div style="background-color: white; margin-right: 0px;" class="row gone">
        <div class="col-md-1"></div>
        <div class="col-md-3" style="margin-right: -104px;">
            <i class=" fa fa-address-book">
            </i>
            <b>Emergency: </b>+01814325325
        </div>
        <div class="col-md-2">
            <span class="fa fa-envelope"></span>
            healthcare@gmail.com
        </div>
        <div class="col-md-4"></div>
        <div class="col-md-2">
            <span class="fa fa-map-marker"></span>
            BGCMed,Chittagong
        </div>
    </div>
    <nav style="background-color: #157fda;" class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand myclass" href="#">
            <img src="~/picture/healthcare3.png" class="logo-img">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="menual collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">

            @if (Session["PatientId"] == null && Session["DoctorId"] == null && Session["ReceptionistId"] == null && Session["AdminId"] == null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white @ViewBag.index" href="@Url.Action("Index", "Health")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link  @ViewBag.Login" href="@Url.Action("Login", "Authentication")">Login</a>
                    <a class="nav-item nav-link  @ViewBag.Registration" href="@Url.Action("Registration", "Authentication")">Registration</a>
                </div>
            }

            @if (Session["PatientId"] != null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white @ViewBag.index" href="@Url.Action("Index","Health")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link  @ViewBag.Appointment" href="@Url.Action("Appointment", "Health")">Appointment</a>
                    <a class="nav-item nav-link  @ViewBag.PatientProfile" href="@Url.Action("PatientProfile", "Health")">Profile</a>
                    <a class="nav-item nav-link  @ViewBag.Notification" href="@Url.Action("Notification", "Health")">Notification<sup><span id="patientnotification" style="display: none;" class="notified fa fa-bell"> @Session["PatientNotification"]</span></sup></a>
                    <a class="nav-item nav-link  @ViewBag.Feedback" href="@Url.Action("Feedback", "Health")">Feedback</a>
                    <a class="nav-item nav-link" href="@Url.Action("PatientLogout", "Authentication")">Logout</a>
                </div>
            }

            @if (Session["DoctorId"] != null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white @ViewBag.Index" href="@Url.Action("Index", "Health")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link  @ViewBag.Prescription" href="@Url.Action("Prescription","Health")">Prescription</a>
                    <a class="nav-item nav-link  @ViewBag.DoctorProfile" href="@Url.Action("DoctorProfile","Health")">Profile</a>
                    <a class="nav-item nav-link" href="@Url.Action("DoctorLogout", "Authentication")">Logout</a>
                </div>
            }

            @if (Session["ReceptionistId"] != null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link text-white @ViewBag.Index" href="@Url.Action("Index","Health")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link  @ViewBag.AppointmentSchedule" href="@Url.Action("AppointmentSchedule", "Health")">Appointment</a>
                    <a class="nav-item nav-link  @ViewBag.Graph" href="@Url.Action("Graph", "Health")">Report</a>
                    <a class="nav-item nav-link  @ViewBag.ReceptionistProfile" href="@Url.Action("ReceptionistProfile","Health")">Profile</a>
                    <a class="nav-item nav-link" href="@Url.Action("ReceptionistLogout", "Authentication")">Logout</a>
                </div>
            }

            @if (Session["AdminId"] != null)
            {
                <div class="navbar-nav">
                    <a class="nav-item nav-link @ViewBag.Index" href="@Url.Action("Index","Health")">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link @ViewBag.Save" href="@Url.Action("Index","DoctorAdmin")">Doctor</a>
                    <a class="nav-item nav-link @ViewBag.ReceptionistCreate " href="@Url.Action("Index", "ReceptionistAdmin")">Receptionist</a>
                    <a class="nav-item nav-link" href="@Url.Action("AdminLogout", "Authentication")">Logout</a>
                </div>
            }

        </div>
    </nav>

    @RenderBody()

    <footer class="footer-distributed">

        <div class="footer-left">
            <p class="footer-company-about">
                <span>BGC TRUST UNIVERSITY</span>
                Afsari Rubaba
            </p>

            <div class="footer-icons">

                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-linkedin-in"></i></a>
                <a href="#"><i class="fab fa-github"></i></a>

            </div>



        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>CDA-5 street</span> Agrabad, Chittagong</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+01814652562</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="#">healthcare@gmail.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <h3>Health<span>Care</span></h3>

            <p class="footer-links">
                We are dedicate to providing the best possible<br> health care for the people to get better health.
            </p>

            <p class="footer-company-name">2020</p>

        </div>

    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*<script>
            var k = parseInt($('#patientnotification').html()) || 0;
            console.log(k);

            if (k > 0) {
                $('#patientnotification').show();
            }

        </script>*@

</body>
</html>